### PR TITLE
Naive algorithm in Rust

### PR DESCRIPTION
**Pull request by xldenis**
Here is a naive algorithm implemented in Rust and verified with Creusot. 
We can't do the Hacker's delight version (at least not yet) as we don't support bitvectors (yet).

### CODE REVIEW

**Comment by rod-chapman** [comment]
I am _really_ trying to get the Von Neumann 1945 algorithm verified... I think I have the loop invariant right now, but the provers aren't happy with it, probably owing to lots of non-linear maths.

Please have a crack at the "classic" binary chop search - that should be relatively easy in Creusot.

**Review by rod-chapman — APPROVED** [review]
Looks good to me.

**Comment by xldenis** [comment]
> Please have a crack at the "classic" binary chop search - that should be relatively easy in Creusot.

I'll do that later. 

> I am really trying to get the Von Neumann 1945 algorithm verified... I think I have the loop invariant right now, but the provers aren't happy with it, probably owing to lots of non-linear maths.

That's the Hacker's Delight one? It seems rather tedious to do without bitvectors but perhaps I'll take a look.

**Comment by rod-chapman** [comment]
The algorithm is Hacker's Delight _is_ Von Neumann's ... it is delightfully non-obvious how it works... I first came across it in about 1996, but had no way of proving it then. I think the team at AdaCore managed to prove it, but had to fall back on Coq to discharge the harder proofs.

**Comment by xldenis** [comment]
Don't look if you don't want the challenge spoiled but here's a why3 version: https://toccata.gitlabpages.inria.fr/toccata/gallery/isqrt_von_neumann.en.html

**Comment by rod-chapman** [comment]
If only I could read Why3! :-) I suspect this implementation was done after Yannick and I asked them for help with the SPARK version...

**Pull request merged**
